### ISSUE TITLE
No module named '_curses'

### ISSUE THREAD

**Issue by Muhimen123** [cSquaerd/CursaTetra#5]
Tried to run the app and got this error 
```
❯ python cursatetra.py
Traceback (most recent call last):
  File "cursatetra.py", line 2, in <module>
    import curses as crs
  File "Y:\Python_3.8.3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by cSquaerd** [comment]
Seems by your file path that you're on Windows; Windows releases of Python don't have **curses** included, though you can use **pip** to install **windows-curses**, and by tests, it should work just find. [link to **windows-curses**](https://pypi.org/project/windows-curses/)

Sorry for the late reply by the way.
